// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Address struct {
	ID        string     `json:"id"`
	Desa      *Desa      `json:"desa"`
	Kecamatan *Kecamatan `json:"kecamatan"`
	Street    string     `json:"street"`
}

type Business struct {
	ID      string   `json:"id"`
	Name    string   `json:"name"`
	Photo   string   `json:"photo"`
	Address *Address `json:"address"`
	User    *User    `json:"user"`
}

type Desa struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Kecamatan *Kecamatan `json:"kecamatan"`
}

type Kecamatan struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type LoginUser struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type NewAddress struct {
	DesaID      string `json:"desa_id"`
	KecamatanID string `json:"kecamatan_id"`
	Street      string `json:"street"`
}

type NewUser struct {
	Name     string      `json:"name"`
	Phone    string      `json:"phone"`
	Password string      `json:"password"`
	Address  *NewAddress `json:"address"`
}

type Order struct {
	ID   string `json:"id"`
	User *User  `json:"user"`
}

type Product struct {
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	Price    string    `json:"price"`
	Photo    string    `json:"photo"`
	Business *Business `json:"business"`
}

type User struct {
	ID       string   `json:"id"`
	Name     string   `json:"name"`
	Phone    string   `json:"phone"`
	Password string   `json:"password"`
	Photo    string   `json:"photo"`
	Address  *Address `json:"address"`
}
