CREATE TABLE IF NOT EXISTS Business(
    ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    Name VARCHAR (127) NOT NULL,
    Phone VARCHAR (127) NULL,
    Photo VARCHAR (127) NULL,
    UserID INT,
    FOREIGN KEY (UserID) REFERENCES User(ID),
    PRIMARY KEY (ID)
)