CREATE TABLE IF NOT EXISTS User(
    ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    Name VARCHAR (127) NOT NULL,
    Phone VARCHAR (127) NOT NULL UNIQUE,
    Password VARCHAR (127) NOT NULL,
    Photo VARCHAR (127) NULL,
    PRIMARY KEY (ID)
)
