CREATE TABLE IF NOT EXISTS Product(
    ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    Name VARCHAR (127) NOT NULL,
    Price INT (10) DEFAULT 0,
    Photo VARCHAR (127) NULL,
    BusinessID INT,
    FOREIGN KEY (BusinessID) REFERENCES Business(ID),
    PRIMARY KEY (ID)
)